### ISSUE TITLE
Problem compiling after upgrade to 1.6.0

### ISSUE THREAD

**Issue by skunktrading** [bxparks/AceCommon#26]
platformio just upgraded my version of AceCommon from 1.5.2 to 1.6.0. Unfortunately I had build errors

In file included from .pio/libdeps/teensy41/AceTime/src/ace_time/ZoneManager.h:16,
                 from .pio/libdeps/teensy41/AceTime/src/AceTime.h:49,
                 from include/Logging.h:45,
                 from src/CapsuleProgress.cpp:4:
.pio/libdeps/teensy41/AceTime/src/ace_time/BasicZone.h: In member function 'ace_common::KString ace_time::BasicZone::kname() const':
.pio/libdeps/teensy41/AceTime/src/ace_time/BasicZone.h:73:66: error: no matching function for call to 'ace_common::KString::KString(const __FlashStringHelper*&, const char* const* const&, const uint8_t&)'
   73 |           name, zoneContext->fragments, zoneContext->numFragments);

I was able to fix it by adding the following to KString.h

    explicit KString(
      const __FlashStringHelper* fs,
      const char* const* keywords,
      uint8_t numKeywords
    ):
      string_(fs),
      keywords_((const void* const*) keywords),
      type_(kTypeFstring),
      numKeywords_(numKeywords > 0x20 ? 0x20 : numKeywords)
    {}

I am building against AceTime 2.2.3

**Comment by skunktrading** [comment]
Sorry. I just looked at the sources of AceTime and it looks like some changes are incoming that will probably resolve this as soon as released.

**Comment by bxparks** [comment]
Ugh, I had intended AceCommon v1.6 to be backwards compatible, but it is now obvious that AceTime would break as soon as I pushed a new version. I got mentally and physically tired from all the coding, and I thought I could save some effort by skipping the 2 additional permutation of those constructor arguments. I'm in the middle of refactoring and feature-adding AceTime and it won't be ready for a release for several days, or a couple of weeks. So I will fix AceCommon and push a new release which should be backwards compatible.
